# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Create tag

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run build
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Andrew Collins
          author_email: me+bot@andrewww.co.uk
          message: 'Automatically add dist directory.'
          add: 'dist --force'
          push: false
      - run: git tag "${{ steps.package-version.outputs.current-version}}"
      - run: git push origin "${{ steps.package-version.outputs.current-version}}"
